// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldgyssrtdddceisxkonm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZ3lzc3J0ZGRkY2Vpc3hrb25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDAxNTUsImV4cCI6MjA1NDk3NjE1NX0.F0Tf3_3ZPxmrszI-TwG1Xei_PLvr-3EgFnOxD_QOoe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);